[build]
  publish = "public"
  command = "streamlit run app.py --server.port $PORT"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
